// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZ5lY33FOUJeV9Yyff5CyYZGbrtygE20',
    appId: '1:32112406340:web:11254d0932a8b811f87111',
    messagingSenderId: '32112406340',
    projectId: 'grocerylistapp-bf738',
    authDomain: 'grocerylistapp-bf738.firebaseapp.com',
    storageBucket: 'grocerylistapp-bf738.appspot.com',
    measurementId: 'G-3ZS0EWL5F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7WlowOEe7kHZA7s3pQ5wbGeclD8ddNmw',
    appId: '1:32112406340:android:66c74ce193645afdf87111',
    messagingSenderId: '32112406340',
    projectId: 'grocerylistapp-bf738',
    storageBucket: 'grocerylistapp-bf738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZTc1neZasMQQlwoA0Kvibu6XicYHRo4',
    appId: '1:32112406340:ios:3770be0d689ebec8f87111',
    messagingSenderId: '32112406340',
    projectId: 'grocerylistapp-bf738',
    storageBucket: 'grocerylistapp-bf738.appspot.com',
    iosClientId: '32112406340-scf7lq8mmcqmupak989og5acuf2782ia.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.brownmit.groceries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZTc1neZasMQQlwoA0Kvibu6XicYHRo4',
    appId: '1:32112406340:ios:a6d2badba3a68b86f87111',
    messagingSenderId: '32112406340',
    projectId: 'grocerylistapp-bf738',
    storageBucket: 'grocerylistapp-bf738.appspot.com',
    iosClientId: '32112406340-dn82ldam3r73ia01khdrk4ncd1i7acec.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.brownmit.groceryListApp',
  );
}
